[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault_mvp = "BHTRWbEGRfJZSVXkJXj1Cv48knuALpUvijJwvuobyvvB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# For Ledger wallet, use: wallet = "usb://ledger"
# For file-based keypair, use: wallet = "keypairs/admin-keypair.json"
wallet = "usb://ledger"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
